### ISSUE TITLE
bug with fill function

### ISSUE THREAD

**Issue by senid231** [influx/influx#1]
wrong text was here

**Comment by Fivell** [comment]
@influx , any update?

**Comment by senid231** [comment]
update screenshots
![image with fill function](https://cloud.githubusercontent.com/assets/8393857/16332625/9a6611b8-39ff-11e6-8aa5-f352c30bcf0b.jpg)
![image without fill function](https://cloud.githubusercontent.com/assets/8393857/16332627/a024bf28-39ff-11e6-85c0-fd075c52d699.jpg)
